const STATUS_DISPONIVEL = 'DISPONIVEL';
const STATUS_INDISPONIVEL = 'INDISPONIVEL';
const STATUS_AGENDADO = 'AGENDADO';
const STATUS_EM_USO = 'EM_USO';

const COINS_GESTORES = 1000;
const COINS_COLAB_TERCEIROS = 1000;

export default {
  STATUS_DISPONIVEL,
  STATUS_INDISPONIVEL,
  STATUS_AGENDADO,
  STATUS_EM_USO,
  COINS_COLAB_TERCEIROS,
  COINS_GESTORES,
};
